
exercise1:
  seed: 1
  token: secret1

exercise2:
  seed: 1
  token: secret2

exercise3:
  token: secret3
  secret_time: 1

exercise4:
  token: secret4

exercise5:
  v0: 0
  v1: 1
  v2: 2
  v3: 3
  token: secret5

exercise6:
  secret: aaaaaa
  token: secret6

exercise8:
  secret:
  token: secret8
